# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('length', models.IntegerField()),
                ('date', models.DateField()),
                ('add_advert', models.BooleanField()),
            ],
        ),
    ]
