# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourses',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentcourses',
            name='student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentCourses',
        ),
    ]
