# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0003_auto_20161207_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='length',
            field=models.PositiveIntegerField(),
        ),
    ]
