# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleshow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='heads',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
