# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleshow', '0002_auto_20161221_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
