# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 09:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleshow', '0005_auto_20161221_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='heads',
        ),
        migrations.RemoveField(
            model_name='program',
            name='start_date',
        ),
        migrations.AddField(
            model_name='program',
            name='advertisement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='broadcast_date',
            field=models.DateField(default=datetime.datetime(2016, 12, 24, 9, 42, 18, 372741)),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.CharField(default='', max_length=200),
        ),
    ]
