# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teleshow', '0006_auto_20161224_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='broadcast_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
