# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='advertisement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='description',
            field=models.CharField(default=b'', max_length=10000),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
