# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161207_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='broadcast_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
