# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telecast_text', models.CharField(max_length=200)),
                ('telecast_length', models.IntegerField(default=0)),
                ('telecast_data', models.DateTimeField(verbose_name='date published')),
                ('telecast_description', models.CharField(max_length=500)),
            ],
        ),
    ]
