# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_name', models.CharField(max_length=20)),
                ('tel_duration', models.IntegerField(default=60)),
                ('tel_descr', models.CharField(max_length=200)),
                ('tel_date', models.DateTimeField(verbose_name='date published')),
                ('tel_adv_op', models.BooleanField(default=1)),
            ],
        ),
    ]
