# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 22:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('duration', models.TimeField(default=datetime.datetime(2016, 12, 10, 22, 14, 37, 949874, tzinfo=utc))),
                ('date', models.DateField(default=datetime.date(2016, 12, 10))),
                ('advert', models.BooleanField(default=False)),
            ],
        ),
    ]
