# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Telecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvprograms',
            name='duration',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
