# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 22:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telecast', '0002_auto_20161210_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvprograms',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
