# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tv_program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('options', models.BooleanField()),
            ],
        ),
    ]
