# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tvprogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=400)),
                ('date', models.DateTimeField()),
                ('adv_option', models.CharField(choices=[('Y', 'Advertisement(Commercial)'), ('N', 'No advertisement(Non commercial)')], max_length=2)),
            ],
        ),
    ]
