# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_product_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='adress',
            new_name='address',
        ),
    ]
