# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('addres', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('status', models.BooleanField(default='false')),
            ],
        ),
    ]
