# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('count', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=50)),
                ('isArrive', models.CharField(default=b'False', max_length=10)),
            ],
        ),
    ]
