# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polis', '0002_auto_20170125_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Shows',
        ),
    ]
