# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polis', '0004_auto_20170125_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
