# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161207_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
