# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('num', models.IntegerField()),
                ('adress', models.TextField(max_length=500)),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
