# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20161204_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('count', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('isArrive', models.BooleanField(default=False)),
            ],
        ),
    ]
