# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='goods',
            name='isArrive',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
