# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoprod',
            old_name='pdor_status',
            new_name='prod_status',
        ),
    ]
