# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='broadcast_date',
            field=models.DateField(default=datetime.datetime(2016, 12, 7, 16, 48, 53, 558018)),
        ),
    ]
