# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_title', models.CharField(max_length=100)),
                ('order_count', models.IntegerField(default=0)),
                ('order_address', models.CharField(max_length=200)),
                ('order_date', models.DateTimeField(verbose_name='order date')),
                ('oredr_status', models.CharField(default='не выполнен', max_length=11)),
            ],
        ),
    ]
