# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprod',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
