# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('running_time', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=250)),
                ('run_date', models.DateTimeField(verbose_name='run date')),
                ('has_ads', models.BooleanField(default=True)),
            ],
        ),
    ]
