# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='has_ads',
            field=models.BooleanField(default=True),
        ),
    ]
