# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.DecimalField(decimal_places=3, max_digits=200)),
                ('discription', models.TextField()),
                ('show_date', models.DateTimeField(verbose_name='date')),
                ('adds', models.CharField(max_length=3)),
            ],
        ),
    ]
