# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='discription',
            new_name='description',
        ),
    ]
