# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20161207_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='show_date',
        ),
        migrations.AddField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='show',
            name='duration',
            field=models.DecimalField(decimal_places=0, max_digits=200),
        ),
    ]
