# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20161207_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='date',
            new_name='show_date',
        ),
    ]
