# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20161207_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
