# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20161207_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='discription',
            field=models.CharField(max_length=200),
        ),
    ]
