# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.DecimalField(decimal_places=0, max_digits=200)),
                ('description', models.CharField(max_length=200)),
                ('show_date', models.DateTimeField(verbose_name='date published')),
                ('adds', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
