# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
