# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('broadcasting_date', models.DateTimeField(verbose_name='')),
                ('contains_advertisement', models.BooleanField(default=False)),
            ],
        ),
    ]
