# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tvprogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='broadcasting_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 7, 16, 24, 15, 545825, tzinfo=utc)),
        ),
    ]
